---
#
# ISSUE 134
#

TOOLS:
  ####
  #### C2  DIRECTORY
  ####

  ####
  #### PIPX
  ####

  - name: pwncat-cs # KO - compilation error
    type: pipx
    source: "pwncat-cs"
    system_site_packages: true
    bin_name: "pwncat-cs"
    link_dir: "{{ SYMLINKS_FARM_STUDENT_TOOL_DIR }}/c2"

  - name: routersploit # KO - need investigations
    type: pipx
    source: "routersploit"
    system_site_packages: true
    bin_name: "routersploit"
    link_dir: "{{ SYMLINKS_FARM_STUDENT_TOOL_DIR }}/c2"

  ####
  #### GOLANG
  ####
