---
#
# ISSUE 134
#

TOOLS:
  ####
  #### web -  DIRECTORY
  ####

  ####
  #### PIPX
  ####

  - name: dirsearch # OK
    type: pipx
    source: "git+https://github.com/maurosoria/dirsearch"
    system_site_packages: true
    bin_name: "dirsearch"
    link_dir: "{{ SYMLINKS_FARM_STUDENT_TOOL_DIR }}/web"

  - name: xsrfprobe # OK
    type: pipx
    source: "git+https://github.com/0xInfection/XSRFProbe"
    system_site_packages: true
    bin_name: "xsrfprobe"
    link_dir: "{{ SYMLINKS_FARM_STUDENT_TOOL_DIR }}/web"

  - name: droopescan # KO bad compilation
    type: pipx
    source: "git+https://github.com/droope/droopescan.git"
    system_site_packages: true
    bin_name: "droopescan"
    link_dir: "{{ SYMLINKS_FARM_STUDENT_TOOL_DIR }}/web"

  - name: cmsmap # OK
    type: pipx
    source: "git+https://github.com/Dionach/CMSmap.git"
    system_site_packages: true
    bin_name: "cmsmap"
    link_dir: "{{ SYMLINKS_FARM_STUDENT_TOOL_DIR }}/web"

  - name: robotstester # OK
    type: pipx
    source: "git+https://github.com/p0dalirius/robotstester"
    system_site_packages: true
    bin_name: "robotstester"
    link_dir: "{{ SYMLINKS_FARM_STUDENT_TOOL_DIR }}/web"

  - name: token-exploiter # OK
    type: pipx
    source: "git+https://github.com/psyray/token-exploiter"
    system_site_packages: true
    bin_name: "token-exploiter"
    link_dir: "{{ SYMLINKS_FARM_STUDENT_TOOL_DIR }}/web"

  - name: wafw00f # OK
    type: pipx
    source: "wafw00f"
    system_site_packages: true
    bin_name: "wafw00f"
    link_dir: "{{ SYMLINKS_FARM_STUDENT_TOOL_DIR }}/web"

  - name: updog # OK
    type: pipx
    source: "updog"
    system_site_packages: true
    bin_name: "updog"
    link_dir: "{{ SYMLINKS_FARM_STUDENT_TOOL_DIR }}/web"

  - name: git-dumper # OK
    type: pipx
    source: "git-dumper"
    system_site_packages: true
    bin_name: "git-dumper"
    link_dir: "{{ SYMLINKS_FARM_STUDENT_TOOL_DIR }}/web"

  - name: arjun # OK
    type: pipx
    source: "arjun"
    system_site_packages: true
    bin_name: "arjun"
    link_dir: "{{ SYMLINKS_FARM_STUDENT_TOOL_DIR }}/web"

  - name: bbot # OK
    type: pipx
    source: "bbot"
    system_site_packages: true
    bin_name: "bbot"
    link_dir: "{{ SYMLINKS_FARM_STUDENT_TOOL_DIR }}/web"

  - name: cewler # OK
    type: pipx
    source: "cewler"
    system_site_packages: true
    bin_name: "cewler"
    link_dir: "{{ SYMLINKS_FARM_STUDENT_TOOL_DIR }}/web"

  # - name: AAA #
  #   type: pipx
  #   source: "AAA"
  #   system_site_packages: true
  #   bin_name: "AAA"
  #   link_dir: "{{ SYMLINKS_FARM_STUDENT_TOOL_DIR }}/active_directory"

  ####
  #### GOLANG
  ####

  - name: gobuster #
    type: go
    module: "github.com/OJ/gobuster/v3@latest"
    version: "latest"
    bin_name: "gobuster"
    link_dir: "{{ SYMLINKS_FARM_STUDENT_TOOL_DIR }}/web"

  - name: hakrawler #
    type: go
    module: "github.com/hakluke/hakrawler@latest"
    version: "latest"
    bin_name: "hakrawler"
    link_dir: "{{ SYMLINKS_FARM_STUDENT_TOOL_DIR }}/web"

  - name: gowitness #
    type: go
    module: "github.com/sensepost/gowitness@latest"
    version: "latest"
    bin_name: "gowitness"
    link_dir: "{{ SYMLINKS_FARM_STUDENT_TOOL_DIR }}/web"

  - name: wuzz #
    type: go
    module: "github.com/asciimoo/wuzz@latest"
    version: "latest"
    bin_name: "wuzz"
    link_dir: "{{ SYMLINKS_FARM_STUDENT_TOOL_DIR }}/web"

  - name: byp4xx #
    type: go
    module: "github.com/lobuhi/byp4xx@latest"
    version: "latest"
    bin_name: "byp4xx"
    link_dir: "{{ SYMLINKS_FARM_STUDENT_TOOL_DIR }}/web"

  - name: nuclei #
    type: go
    module: "github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest"
    version: "latest"
    bin_name: "nuclei"
    link_dir: "{{ SYMLINKS_FARM_STUDENT_TOOL_DIR }}/web"

  - name: hakrevdns #
    type: go
    module: "github.com/hakluke/hakrevdns@latest"
    version: "latest"
    bin_name: "hakrevdns"
    link_dir: "{{ SYMLINKS_FARM_STUDENT_TOOL_DIR }}/web"

  - name: hakrevdns #
    type: go
    module: "github.com/hakluke/hakrevdns@latest"
    version: "latest"
    bin_name: "hakrevdns"
    link_dir: "{{ SYMLINKS_FARM_STUDENT_TOOL_DIR }}/web"

  - name: httprobe #
    type: go
    module: "github.com/tomnomnom/httprobe@latest"
    version: "latest"
    bin_name: "httprobe"
    link_dir: "{{ SYMLINKS_FARM_STUDENT_TOOL_DIR }}/web"

  - name: httpx #
    type: go
    module: "github.com/projectdiscovery/httpx/cmd/httpx@latest"
    version: "latest"
    bin_name: "httpx"
    link_dir: "{{ SYMLINKS_FARM_STUDENT_TOOL_DIR }}/web"

  - name: anew #
    type: go
    module: "github.com/tomnomnom/anew@latest"
    version: "latest"
    bin_name: "anew"
    link_dir: "{{ SYMLINKS_FARM_STUDENT_TOOL_DIR }}/web"

  - name: naabu #
    type: go
    module: "github.com/projectdiscovery/naabu/v2/cmd/naabu@latest"
    version: "latest"
    bin_name: "naabu"
    link_dir: "{{ SYMLINKS_FARM_STUDENT_TOOL_DIR }}/web"

  - name: jsluice #
    type: go
    module: "github.com/BishopFox/jsluice/cmd/jsluice@latest"
    version: "latest"
    bin_name: "jsluice"
    link_dir: "{{ SYMLINKS_FARM_STUDENT_TOOL_DIR }}/web"

  - name: katana #
    type: go
    module: "github.com/projectdiscovery/katana/cmd/katana@latest"
    version: "latest"
    bin_name: "katana"
    link_dir: "{{ SYMLINKS_FARM_STUDENT_TOOL_DIR }}/web"

  - name: ffuf #
    type: go
    module: "https://github.com/ffuf/ffuf@latest"
    version: "latest"
    bin_name: "ffuf"
    link_dir: "{{ SYMLINKS_FARM_STUDENT_TOOL_DIR }}/web"
#
# - name: AAAA #
#   type: go
#   module: "github_AAAA@latest"
#   version: "latest"
#   bin_name: "AAAA"
#   link_dir: "{{ SYMLINKS_FARM_STUDENT_TOOL_DIR }}/network"
