---
#
# ISSUE 134
#

TOOLS:
  ####
  ####  WIFI -  DIRECTORY
  ####

  ####
  #### PIPX
  ####

  ####
  #### GOLANG
  ####

  # - name: bettercap #
  #   type: go
  #   module: "github.com/bettercap/bettercap/v2"
  #   version: "latest"
  #   bin_name: "bettercap"
  #   link_dir: "{{ SYMLINKS_FARM_STUDENT_TOOL_DIR }}/network"

  # - name: AAAA #
  #   type: go
  #   module: "github_AAAA@latest"
  #   version: "latest"
  #   bin_name: "AAAA"
  #   link_dir: "{{ SYMLINKS_FARM_STUDENT_TOOL_DIR }}/network"
