---
# handlers file

- name: restart apt-cacher-ng
  ansible.builtin.systemd:
    name: apt-cacher-ng
    state: restarted
  become: true

- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
  become: true
