---
- name: Install | Package mode
  ansible.builtin.include_tasks: package/install.yml
  when: headscale_install_mode == "package"

- name: Install | Docker mode
  ansible.builtin.include_tasks: docker/install.yml
  when: headscale_install_mode == "docker"
