#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

- name: install - basics packages - block
  block:
    #
    # - name: INCLUDE - remove packages - debian-based
    #   ansible.builtin.include_tasks: ./debian-based/packages_basics.yaml
    #   when: ansible_facts.distribution in ['Ubuntu', 'Debian']
    #
    - name: INCLUDE - remove packages - fedora
      ansible.builtin.include_tasks: ./fedora/remove_cockpit.yaml
      when: ansible_facts.distribution == 'Fedora'

  when: (SPECIFIC_PACKAGES_CLEANING | default('no') | string | lower) in ['yes', 'true']
  # when: SPECIFIC_PACKAGES_CLEANING | default('NO') == 'YES'

