#
# ISSUE 117
#

services:
  sudo-cve-2025-32462: &main # set main anchor.
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sudo-cve-2025-32462
    ports:
      - "1112:8080"
    restart: unless-stopped
    command: ["sleep", "infinity"]
#
# #### #### do not remove.
#
#   debug:
#     <<: *main
#     container_name: sudo-cve-2025-32462-debug
#     ports:
#       - "60443:443"
#     command: ["sleep", "infinity"]
#     # command: ["/bin/bash"]
