---
# #

- block:
    ####
    #### WARMUP - packages structure checks
    ####

    - name: CHECK - IS TREE EXIST ?
      file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop: "{{ tools | map(attribute='link_dir') | select('defined') | unique | list }}"
      loop_control:
        label: "{{ item }}"

    ####
    #### SETUP PRE REQUIRED PACKAGES
    ####

    - name: PRE REQUIRED PACKAGES (by type)
      ansible.builtin.include_tasks: "{{ item }}"
      loop:
        - warmup_install_pipx.yml
        - warmup_install_golang.yml
        - warmup_install_apt.yml

    ####
    #### INSTALL PIPX TOOLS
    ####

    - name: Install pipx packages
      vars:
        pipx_args: >-
          {{ '--system-site-packages' if (item.system_site_packages | default(false)) else '' }}
      community.general.pipx:
        name: "{{ item.source | default(item.name) }}"
        state: present
        install_deps: true
        editable: false
        inject_packages: "{{ item.pip_args | default(omit) }}"
        pip_args: "{{ item.pip_args | default(omit) }}"
        executable: "pipx"
      loop: "{{ tools }}"
      when: item.type == 'pipx'

    #
    # BUILD ENV LIST + CHECKS
    #
    - name: BUILD VENV LINKS LINST - PIPX
      vars:
        _venv: "{{ item.venv_name | default(item.name) }}"
        _bin: "{{ item.bin_name  | default(item.name) }}"
        _src: "{{ SYMLINKS_FARM_STUDENT_HOME_DIR }}/.local/share/pipx/venvs/{{ _venv }}/bin/{{ _bin }}"
        _dest: "{{ item.link_dir }}/{{ item.link_name | default(_bin) }}"
      set_fact:
        _links: "{{ (_links | default([])) + [ {'name': item.name, 'src': _src, 'dest': _dest} ] }}"
      loop: "{{ tools }}"
      when: item.type == 'pipx'

    - name: STAT PIPX LINKS SOURCES
      stat:
        path: "{{ item.src }}"
      loop: "{{ _links }}"
      register: pipx_link_stats

    # - name: DEBUG
    #   debug:
    #     var: pipx_link_stats

    #
    # FINALIZE
    #

    - name: CREATE SYMLINKS FROM PIPX ENV
      file:
        src: "{{ item.item.src }}"
        dest: "{{ item.item.dest }}"
        state: link
        force: true
      loop: "{{ pipx_link_stats.results }}"
      when: item.stat.exists
      loop_control:
        label: "{{ item.item.dest }} -> {{ item.item.src }}"

  vars:
    tools:
      - name: maigret
        type: pipx
        source: "git+https://github.com/soxoj/maigret.git"
        system_site_packages: true # optionnel
        bin_name: "maigret"
        link_dir: "{{ SYMLINKS_FARM_STUDENT_TOOL_DIR }}/osint" # le lien final sera .../maigret

      - name: gitfive
        type: pipx
        source: "git+https://github.com/mxrch/gitfive.git"
        # source: "git+https://github.com/mxrch/GitFive.git#egg=gitfive"

        system_site_packages: true # optionnel
        bin_name: "gitfive"
        link_dir: "{{ SYMLINKS_FARM_STUDENT_TOOL_DIR }}/osint" # le lien final sera .../maigret

