---
- name: cleaning - remove useless packages

  block:
    - name: cleaning - remove useless packages - disable cockpit service - fedora
      systemd:
        name: cockpit.socket
        state: stopped
        enabled: no
      when: ansible_facts.distribution == 'Fedora'
      become: true

    - name: cleaning - remove useless packages - remove cockpit package - fedora
      dnf:
        name: cockpit
        state: absent
      when: ansible_facts.distribution == 'Fedora'
      become: true
