---

- name: install - update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: install - install apt-cacher-ng
  ansible.builtin.apt:
    name: apt-cacher-ng
    state: present
  become: true
