---
#

- name: install - basics packages - fedora
  dnf:
    name:
      - git
      - zsh
      - vim
      - dnf-plugins-core # fix - check reboot
      - unzip
      - tar
      - curl

    state: present
    update_cache: yes

  when: ansible_facts.distribution == 'Fedora'
