export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="gentoo"
DISABLE_AUTO_UPDATE="true"

source $ZSH/oh-my-zsh.sh
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin"

alias grep='grep --color=auto'
alias ls='LC_COLLATE=C ls --color -h --group-directories-first'
alias l='LC_COLLATE=C ls -l'
alias llg="ls -lah | grep -i $1" 

discovery() { find -type f -exec file '{}' ';' } 
discoverySimilar() { find -type f -exec md5sum '{}' ';' | sort | uniq --all-repeated=separate -w 33 }

