#!/usr/bin/env bash
# ISSUE 142 — generates Gitea API token per user; tokens are used for docker login
set -euo pipefail

TOKENS_DIR="/tokens"
CREDS_FILE="${TOKENS_DIR}/gitea-registry-credentials.json"
TOKENS_FILE="${TOKENS_DIR}/tokens.txt"

GITEA_URL="$(jq -r '.baseurl' "${CREDS_FILE}")"

echo "[provision-tokens] Generating registry tokens ..."
printf '# Generated by gitea-registry provisioner\n' > "${TOKENS_FILE}"
printf '# docker login usage: docker login DOMAIN:PORT -u USERNAME -p TOKEN\n' >> "${TOKENS_FILE}"

jq -c '.users[]' "${CREDS_FILE}" | while IFS= read -r entry; do
  username="$(printf '%s' "${entry}" | jq -r '.username')"
  password="$(printf '%s' "${entry}" | jq -r '.password')"

  token_resp=$(curl -sf \
    -X POST "${GITEA_URL}/api/v1/users/${username}/tokens" \
    -u "${username}:${password}" \
    -H "Content-Type: application/json" \
    -d '{"name":"registry-token"}' 2>/dev/null || printf '{}')

  token_val="$(printf '%s' "${token_resp}" | jq -r '.sha1 // empty')"
  if [ -z "${token_val}" ]; then
    echo "[warn] No token returned for ${username} — check provisioner logs"
    token_val="ERROR"
  else
    echo "[provision-tokens]   + ${username}"
  fi
  printf '%s:%s\n' "${username}" "${token_val}" >> "${TOKENS_FILE}"
done

chmod 600 "${TOKENS_FILE}"
echo "[provision-tokens] Done. Tokens → ${TOKENS_FILE}"
