#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

- name: install - basics packages - block
  block:
    #
    - name: INCLUDE - install - utils_json packages - ubuntu
      ansible.builtin.include_tasks: ./ubuntu/utils_json.yaml
      when: ansible_facts.distribution == 'Ubuntu'
    #
    - name: INCLUDE - install - utils_json packages - fedora
      ansible.builtin.include_tasks: ./fedora/utils_json.yaml
      when: ansible_facts.distribution == 'Fedora'

  when: INSTALL_PACKAGES_UTILS_JSON | default('NO') == 'YES'

