#!/usr/bin/env bash
#
# ISSUE 146
#
# provision-tokens.sh — generates a Nextcloud app password for every user in
# nc-credentials.json and appends the result to /tokens/tokens.txt.
#
# App passwords are generated by calling POST /ocs/v2.php/core/apppassword
# while authenticated as the target user (Nextcloud only issues app passwords
# for the currently-authenticated principal).
#
set -euo pipefail

TOKENS_DIR="/tokens"
CREDS_FILE="${TOKENS_DIR}/nc-credentials.json"
TOKENS_FILE="${TOKENS_DIR}/tokens.txt"

if [ ! -f "${CREDS_FILE}" ]; then
  echo "[provision-tokens] ERROR: credentials file not found: ${CREDS_FILE}"
  exit 1
fi

NC_URL="$(jq -r '.baseurl' "${CREDS_FILE}")"

: > "${TOKENS_FILE}"
chmod 600 "${TOKENS_FILE}"

echo "[provision-tokens] Generating app passwords ..."

generate_token() {
  local username="$1" password="$2"
  local resp app_pass

  resp=$(curl -sf -X POST "${NC_URL}/ocs/v2.php/core/apppassword" \
    -u "${username}:${password}" \
    -H "OCS-APIRequest: true" \
    -H "Accept: application/json" \
    || echo '{}')

  app_pass=$(printf '%s' "${resp}" | jq -r '.ocs.data.apppassword // "ERROR"' 2>/dev/null || echo "ERROR")

  if [ "${app_pass}" = "ERROR" ] || [ -z "${app_pass}" ]; then
    echo "[provision-tokens]   WARN: could not generate app password for ${username}"
    return
  fi

  printf '%s:%s\n' "${username}" "${app_pass}" >> "${TOKENS_FILE}"
  echo "[provision-tokens]   + token: ${username}"
}

while IFS= read -r entry; do
  username=$(printf '%s' "${entry}" | jq -r '.username')
  password=$(printf '%s' "${entry}" | jq -r '.password')
  generate_token "${username}" "${password}"
done < <(jq -c '.users[]' "${CREDS_FILE}")

echo "[provision-tokens] App passwords written to ${TOKENS_FILE}."
