server {
    listen 80;
    server_name _;

    location /healthz {
        return 200 "ok\n";
        add_header Content-Type text/plain;
    }

    location /acng-report.html {
        proxy_pass http://apt-cacher-ng:3142/acng-report.html;
    }

    location / {
        proxy_pass http://apt-cacher-ng:3142/;
    }
}
