---
#

##
## Issue : 7
##

- name: INCLUDE - install - ntp and time update
  ansible.builtin.include_tasks: ./include/network/ntp_client/_main.yaml
  when: INSTALL_PACKAGES_NTP_AND_UPDATE_TIME | default('NO') == 'YES'

#
- name: INCLUDE - install - basic packages
  ansible.builtin.include_tasks: ./include/packages-sets/basics/_main.yaml
  when: INSTALL_PACKAGES_BASICS | default('NO') == 'YES'

#
- name: INCLUDE - install - firewalls
  ansible.builtin.include_tasks: ./include/network/firewalls/_main.yaml
  when: INSTALL_PACKAGES_FIREWALLS | default('NO') == 'YES'

#

- block:
    - name: INCLUDE - install - docker
      ansible.builtin.include_tasks: ./include/docker/_main.yaml
      when: INSTALL_PACKAGES_DOCKER | default('NO') == 'YES'

    #
    - name: INCLUDE - install - docker-compose
      ansible.builtin.include_tasks: ./include/docker/_main.yaml
      when:
        - INSTALL_PACKAGES_DOCKER_COMPOSE | default('NO') == 'YES'
        - INSTALL_PACKAGES_DOCKER | default('NO') == 'YES'

#
- name: INCLUDE - install - utils - json
  ansible.builtin.include_tasks: ./include/packages-sets/utils/json/_main.yaml
  when: INSTALL_PACKAGES_UTILS_JSON | default('NO') == 'YES'

#
- name: INCLUDE - install - utils - network
  ansible.builtin.include_tasks: ./include/packages-sets/utils/network/_main.yaml
  when: INSTALL_PACKAGES_UTILS_NETWORK | default('NO') == 'YES'

- name: INCLUDE - specific - cleaning
  ansible.builtin.include_tasks: ./include/packages-sets/cleaning/_main.yaml
  when: SPECIFIC_PACKAGES_CLEANING | default('NO') == 'YES'
